# do not build on tags (GitHub and BitBucket)
skip_tags: true

# skip commits if it's media/docs only
skip_commits:
  files:
    - '**/*.md'
    - '**/images/*'
    - '**/icons/*'

image: Visual Studio 2017

# restor NuGet packages
before_build:
  - nuget restore src\Codit.ApiApps.ActiveDirectory.sln
  - cmd: echo %appveyor_build_version%

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: Any CPU

# build configuration, i.e. Debug, Release, etc.
configuration: Release

# only build master branch
branches:
  only:
  - master

pull_requests:
  do_not_increment_build_number: true

# build solution
build:
  parallel: true
  project: src/Codit.ApiApps.ActiveDirectory.sln
  verbosity: minimal

# test solution
test:
  categories:
    only:
    - Unit